name: Mailtrap test

on:
  pull_request:
    branches:
      - main 
    paths:
      - '**'

jobs:
    mailtrap-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 18
        - name: Install dependencies
          run: npm install
        - name: Mailtrap test
          env:
            MAILTRAP_USERNAME: ${{ secrets.MAILTRAP_USERNAME }}
            MAILTRAP_PASSWORD: ${{ secrets.MAILTRAP_PASSWORD }}
          run: npm run test-mailtrap-njk ./src/njk/templates/submission-email.njk # Run the mailtrap-njk.js script
